language: python # => 1
    python:
	- Python 3.8.5
    env:
      -DJANGO=3.1.2
    install:
      - pip install -r GiftcardSite/requirements.txt
    script:
      - python GiftcardSite/manage.py test GiftcardSite
