language: python # => 1
    python:
	- Python 3.8.5
    services:
      - mysql
    env: # => 4
      -DJANGO=3.1.2 DB=mysql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - mysql -e 'create database test;' -u root
    script:
      - python manage.py test
